Placeholder notebook for implementation trials/tests

In [1]:
import torch

ashape = (3, 1, 4, 4)

a = torch.cat((torch.ones(ashape).unsqueeze(dim=0), 2 * torch.ones(ashape).unsqueeze(dim=0)), dim=0)

In [16]:
a.shape

torch.Size([2, 3, 1, 4, 4])

In [19]:
b = a.chunk(2, dim=0)

b[0].squeeze(dim=0), b[1].squeeze(dim=0)

(tensor([[[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],
 
 
         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],
 
 
         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]]]),
 tensor([[[[2., 2., 2., 2.],
           [2., 2., 2., 2.],
           [2., 2., 2., 2.],
           [2., 2., 2., 2.]]],
 
 
         [[[2., 2., 2., 2.],
           [2., 2., 2., 2.],
           [2., 2., 2., 2.],
           [2., 2., 2., 2.]]],
 
 
         [[[2., 2., 2., 2.],
           [2., 2., 2., 2.],
           [2., 2., 2., 2.],
           [2., 2., 2., 2.]]]]))

In [1]:
a = 'cuda'
b = 'cuda:0'

def extract_devicetype(device: str) -> list[str]:
    return device.split(':')


tuple(map(extract_devicetype, (a, b)))

(['cuda'], ['cuda', '0'])

In [6]:
a = torch.zeros(10)

a.mean(), a.mean(dim=0)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [8]:
list(range(10)), list(range(1, 10)), list(range(1, 11))

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [1, 2, 3, 4, 5, 6, 7, 8, 9],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [14]:
list(enumerate(range(10))), list(enumerate(range(1, 11), start=6))

([(0, 0),
  (1, 1),
  (2, 2),
  (3, 3),
  (4, 4),
  (5, 5),
  (6, 6),
  (7, 7),
  (8, 8),
  (9, 9)],
 [(6, 1),
  (7, 2),
  (8, 3),
  (9, 4),
  (10, 5),
  (11, 6),
  (12, 7),
  (13, 8),
  (14, 9),
  (15, 10)])

In [16]:
import torch
import torch.nn as nn

b, c = 1, 1

dshape = (b, c, 11, 15)
mshape = (b, c, 21, 25)

pad_n, pad_m = dshape[-2] - 1, dshape[-1] - 1
pad_mode = torch.nn.ConstantPad2d((pad_m, pad_m, pad_n, pad_n), 0)

detector = torch.zeros(dshape)
mask = pad_mode(torch.zeros(mshape))

sky = torch.conv2d(mask, detector)

sshape = sky.shape
assert mask.shape == torch.Size([1, 1, 41, 53]), f'Current padded mask shape is: {mask.shape}'
assert sshape == torch.Size([1, 1, 31, 39]), f'Current sky shape is: {sshape}'

In [ ]:
dspath: str = '/mnt/d/PhD_AASS/Coding/Images_fits/irosdiffsn_dataset_ID1_nels100.pickle'

data: dict[str, Any] = load_pickle(dspath)

In [12]:
data['camera'].keys()

dict_keys(['specs', 'upsampling', 'arrays', 'data_shape', 'bins'])

In [ ]:
field = data['data']
sgs, gtpars = map(torch.tensor, (tuple(field.values())))

In [11]:
sgs.shape

torch.Size([100, 308, 1264])

In [24]:
a = torch.poisson(torch.ones((3, 1, 5, 5)))

mask = (a > 0).float()

# a[mask].mean(dim=(-2, -1)), a.mean(dim=(-2, -1))

els = mask.sum(dim=(-2, -1), keepdim=True)

mu = a.sum(dim=(-2, -1), keepdim=True) / els

std = torch.sqrt(
    ((a - mu) ** 2).sum(dim=(-2, -1), keepdim=True) / els
)

b = (a - mu) / std


b.mean(dim=(-2, -1)), b.std(dim=(-2, -1))

(tensor([[-0.4507],
         [-0.3996],
         [-0.3478]]),
 tensor([[0.5370],
         [0.7640],
         [0.7899]]))

In [1]:
import torch


a = torch.poisson(10 * torch.ones((3, 1, 5, 5)))

a.sum(), a.mean(), a.median(), a.std(), a.max(), a.min()

(tensor(725.),
 tensor(9.6667),
 tensor(9.),
 tensor(3.2522),
 tensor(19.),
 tensor(3.))

In [2]:
b = (a - a.median()) / a.std()

b.sum(), b.mean(), b.median(), b.std(), b.max(), b.min()

(tensor(66.7125),
 tensor(0.0002),
 tensor(0.),
 tensor(1.),
 tensor(6.0073),
 tensor(-3.1618))

In [3]:
a = torch.poisson(20 * torch.ones((500, 300, 1200)))
b = a.amax(dim=(-2, -1))

b.mean(), b.std()

(tensor(44.0540), tensor(1.6026))

In [ ]:
from pkdev.dataset import get_dataset, get_dataloaders

dirpath: str = '/mnt/dbb8f47e-da06-47bf-8ef5-038092af70f7/Edos_Magnificent_Manor/PhD_AASS/Coding/IROS_Diffusion/IROSdiffusion_datasets'

data = get_dataset(dirpath)

Loading Data: 1it [00:00,  5.86it/s]

Loading...
Data loaded!
Loading...


Loading Data: 3it [00:00,  6.27it/s]

Data loaded!
Loading...
Data loaded!


In [3]:
sgs = data.shadowgrams

In [ ]:
sgs[:10].unsqueeze(dim=1).mean(dim=(-2, -1))

TypeError: median() received an invalid combination of arguments - got (dim=tuple, ), but expected one of:
 * ()
      didn't match because some of the keywords were incorrect: dim
 * (int dim, bool keepdim = False)
 * (name dim, bool keepdim = False)
